# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.msQuantile <- function(left, right, n, nsim, verbose) {
    .Call('_essHist_msQuantile', PACKAGE = 'essHist', left, right, n, nsim, verbose)
}

.boundedHistogram <- function(orderedData, start, rightIndex, lower, upper) {
    .Call('_essHist_boundedHistogram', PACKAGE = 'essHist', orderedData, start, rightIndex, lower, upper)
}

