# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.msQuantile <- function(n, nsim) {
    .Call('_essHist_msQuantile', PACKAGE = 'essHist', n, nsim)
}

.boundedHistogram <- function(cumSum, start, rightIndex, lower, upper) {
    .Call('_essHist_boundedHistogram', PACKAGE = 'essHist', cumSum, start, rightIndex, lower, upper)
}

